version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: supportdesk-db
    environment:
      POSTGRES_DB: supportdesk_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U supportdesk_user -d supportdesk_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: