spring:
  application:
    name: ${APP_NAME:supportdesk}

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false

    hibernate:
      ddl-auto: validate

    show-sql: ${JPA_SHOW_SQL:true}

    properties:
      hibernate:
        format_sql: ${JPA_FORMAT_SQL:true}
        jdbc:
          time_zone: UTC

  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    baseline-on-migrate: false
    locations: classpath:db/migration
    validate-on-migrate: true

server:
  port: ${SERVER_PORT:8080}